name: Keepalive

on:
  workflow_dispatch:
  # <cron_description>
  schedule:
    - cron: '<cron>'

jobs:
  keepalive:
    name: Keepalive
    # Only run cron on the <account> account
    if: (github.event_name == 'schedule' && github.repository_owner == '<account>') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
