name: Keepalive

on:
  schedule:
    - cron: '<cron>'
  workflow_dispatch:

jobs:
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
